Update trend_bank.py
Fix for Fast learnable ema error:
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2048, 7]], which is output 0 of AsStridedBackward0, is at version 512; expected version 511 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).